sudo: required

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

before_install:
  - docker build -t murphylab/cellorganizer .

script:
  - docker images -a
  - docker containers -a 
  - docker run -d murphylab/cellorganizer /bin/sh -c "tree ."